{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total books sold",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_books_sold", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of executors",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "number_of_executors_gauge", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "New order traces",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "3a41b96f", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "observability" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [ "new_order" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Total order attempts",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "orders_started_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Orders processed",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 6, "y": 4 },
   "targets": [
    { "expr": "orders_proccessed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "New order to queue traces",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 7 },
   "targets": [
    {
     "filters": [
      { "id": "1300d093", "operator": "=", "scope": "span" },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [ "new_order_to_queue" ],
       "valueType": "string"
      },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "observability" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Total orders sent to queue",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "orders_sent_to_queue_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Order queue length",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 6, "y": 8 },
   "targets": [
    { "expr": "queue_length_gauge_orders", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Order size",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "average_order_size_books_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Order execution time",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "order_executor_processing_time_seconds_bucket",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}